l1 = 0
b1 = 0
b2 = 0
auth_l=0
auth_p=0
ent_l =0
ent_p =0
ent_b =0
grateFullOutput = 0
outputLabel = 0
introLabel= 0
viewPeopleButton = 0
deleteButton = 0 
insertButton = 0
updateButton = 0
showSuccessfullDeletion = 0
infoLabel= 0
deleteUserLoginEntry = 0
deleteUserB = 0
infoLabelInsert = 0
infoId = 0
idEntry = 0
infoName = 0
nameEntry = 0
infoSurname = 0
surnameEntry = 0
infoLogin = 0
loginEntry = 0
infoPassword = 0
passwordEntry= 0
insertB = 0
loginOfNeededUser = 0
loOfUser = 0
userEntry = 0
newNameLabel = 0 
newNameEntry = 0
newSurnameLabel = 0
newSurnameEntry = 0
finalButtonUpdate = 0
regInformation =0
regIdLabel = 0
regIdEntry = 0
regNameLabel =0 
regNameEntry = 0
regSurnameLabel =0  
regSurnameEntry =0
regLoginLabel = 0
regLoginEntry = 0
regPaswwordLabel =0 
regPasswordEntry = 0
regButton = 0